export default [
  {
    id: 1,
    name: "Holi Hai",
    location: "Bangalore",
    timing: "14th March, 1000Hrs",
    price: 2200,
    no_passes: 200,
  },
  {
    id: 2,
    name: "The rockerss",
    location: "Bangalore",
    timing: "17th March, 2000Hrs",
    price: 3500,
    no_passes: 300,
  },
  {
    id: 3,
    name: "IMParty",
    location: "Mumbai",
    timing: "24th March, 1600Hrs",
    price: 2400,
    no_passes: 900,
  },
  {
    id: 4,
    name: "TekHouse",
    location: "Delhi",
    timing: "29th March, 2200Hrs",
    price: 3200,
    no_passes: 80,
  },
  {
    id: 5,
    name: "TekHouse",
    location: "Delhi",
    timing: "29th March, 2200Hrs",
    price: 3200,
    no_passes: 80,
  },
  {
    id: 6,
    name: "TekHouse",
    location: "Delhi",
    timing: "29th March, 2200Hrs",
    price: 3200,
    no_passes: 80,
  },
  {
    id: 7,
    name: "TekHouse",
    location: "Delhi",
    timing: "29th March, 2200Hrs",
    price: 3200,
    no_passes: 80,
  },
  {
    id: 8,
    name: "TekHouse",
    location: "Delhi",
    timing: "29th March, 2200Hrs",
    price: 3200,
    no_passes: 80,
  },
];
